name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install GitHub CLI
      run: sudo apt-get install gh

    - name: Authenticate with GitHub CLI
      run: gh auth login --with-token < ${secrets.GHCR_TOKEN}

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u professor-tucker --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/professor-tucker/docker-llm:latest .
        docker push ghcr.io/professor-tucker/docker-llm:latest
